language: python
python:
  - 3.6.3
install:
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt
before_script:
  - export FLASK_DEBUG=1
script:
  - git submodule init
  - cd vyper && make && cd ..
  - flask test